# Generated by Django 4.1.7 on 2023-04-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register_customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=100, unique=True)),
                ('Name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Register_customer',
            },
        ),
    ]
